version: 0.1

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
      - npm install -g serverless
      - npm install -S serverless-finch
      - npm install -S serverless-dynamodb-client
  build:
    commands:
      - whoami
      - sls help
  post_build:
    commands:
      - serverless deploy
artifacts:
  files:
    - serverless.yml
    - publish.zip
  discard-paths: yes
