version: 0.1

phases:
  install:
    commands:
      - apt-get -y update
      - apt-get -y install zip
      - npm install -g serverless@1.9.0
      - npm install -g serverless-finch
      - npm install -g serverless-dynamodb-client
  build:
    commands:
      - whoami
  post_build:
    commands:
      - serverless deploy -stage $env -region us-east-1 –verbose
artifacts:
  files:
    - serverless.yml
    - publish.zip
  discard-paths: yes
